name: Availability

on:
  schedule:
    - cron: "*/30 7-21 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Scraper
        run: echo "found=$(python scrape_availability.py)" >> "$GITHUB_OUTPUT"
        id: scrape
      - name: Debug
        run: |
          echo found is ${{steps.scrape.outputs.found}} 
          echo STOCK is ${{ env.STOCK }}
      - name: Send mail
        if: steps.scrape.outputs.found == 1
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Disponibilidad de uniformes jesuitas
          to: juan.elosua@gmail.com
          body: "Uniformes en jesuitas: ${{env.STOCK}}"
          from: Automated Email
          ignore_cert: true
          secure: true